import React, { useState } from 'react';
import { FiDownload, FiSave, FiRefreshCw } from 'react-icons/fi';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

const AnalysisDisplay = ({ analysis, title, author, onSaveToHistory, onRegenerate }) => {
  const [activeTab, setActiveTab] = useState('meanings');

  const tabs = [
    { id: 'meanings', label: 'Meanings & Vocabulary' },
    { id: 'literaryDevices', label: 'Literary Devices' },
    { id: 'themes', label: 'Themes' },
    { id: 'symbolism', label: 'Symbolism' },
    { id: 'historicalContext', label: 'Context' },
    { id: 'summary', label: 'Summary' },
  ];

  const handleDownload = () => {
    const content = `
LITERARY ANALYSIS
================

Work: ${title || 'Untitled'}
Author: ${author || 'Unknown'}

ANALYSIS REPORT
---------------

${tabs.map(tab => `
${tab.label.toUpperCase()}
${'-'.repeat(tab.label.length)}
${analysis[tab.id] || 'N/A'}

`).join('')}

Generated by Literature Analysis AI
    `.trim();

    const element = document.createElement('a');
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(content));
    element.setAttribute('download', `${title || 'analysis'}.txt`);
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="bg-zinc-400 rounded-xl shadow-lg overflow-hidden border border-zinc-300">
      <div className="bg-gradient-to-r from-lime-600 to-lime-500 p-6 text-white">
        <h2 className="text-2xl font-bold bg-gradient-to-r from-white via-lime-100 to-white bg-clip-text text-transparent drop-shadow-lg">{title || 'Analysis Results'}</h2>
        <p className="text-lime-100 text-sm mt-1">by {author || 'Unknown'}</p>
      </div>

      {/* Tabs */}
      <div className="border-b border-zinc-300">
        <div className="overflow-x-auto">
          <div className="flex gap-2 p-4 min-w-max">
            {tabs.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`px-4 py-2 rounded-lg font-semibold transition whitespace-nowrap ${
                  activeTab === tab.id
                    ? 'bg-lime-600/20 text-lime-600 border-b-2 border-lime-500'
                    : 'text-zinc-700 hover:text-zinc-900 hover:bg-zinc-300'
                }`}
              >
                {tab.label}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="p-6">
        <div className="prose prose-sm max-w-none">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {analysis[activeTab] || 'No content available'}
          </ReactMarkdown>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="border-t border-zinc-300 p-6 bg-zinc-400 flex gap-3">
        <button
          onClick={onSaveToHistory}
          className="flex-1 flex items-center justify-center gap-2 bg-lime-600 text-white font-semibold py-3 rounded-lg hover:bg-lime-700 transition"
        >
          <FiSave size={20} />
          Save to History
        </button>
        <button
          onClick={handleDownload}
          className="flex-1 flex items-center justify-center gap-2 bg-zinc-300 text-lime-600 font-semibold py-3 rounded-lg hover:bg-zinc-200 border border-lime-500/50 transition"
        >
          <FiDownload size={20} />
          Download
        </button>
        <button
          onClick={onRegenerate}
          className="flex-1 flex items-center justify-center gap-2 bg-blue-600 text-white font-semibold py-3 rounded-lg hover:bg-blue-700 transition"
        >
          <FiRefreshCw size={20} />
          Regenerate
        </button>
      </div>
    </div>
  );
};

export default AnalysisDisplay;
